services:
  - type: web
    name: infinite-canvas
    runtime: docker
    plan: free
    autoDeployTrigger: off
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
      - key: S3_REGION
        value: rainyun
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: STORAGE_API_TOKEN
        generateValue: true
